# .github/workflows/deploy.yml
name: "Deploy to Production"
on:
  workflow_run:
    workflows: ["Ruby on Rails CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Download precompiled assets
        uses: actions/download-artifact@v4
        with:
          name: precompiled-assets
          path: ./
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Hatchbox
        uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
